# golangci-lint configuration for WeaverTools
# This configuration enables linters for code quality, security, style, and best practices.

run:
  # Timeout for analysis (set high for CI environments)
  timeout: 5m

  # Include test files in analysis
  tests: true

  # Number of operating system threads
  concurrency: 4

  # Allow multiple parallel golangci-lint instances
  allow-parallel-runners: true

  # Go version to use for analysis
  go: "1.23"

  # Directories to skip
  skip-dirs:
    - vendor
    - .git

linters:
  # Disable all linters by default and explicitly enable ones we want
  disable-all: true

  enable:
    # Core linters - essential for any Go project
    - gofmt        # Checks if code is gofmt-ed
    - govet        # Reports suspicious constructs
    - errcheck     # Checks for unchecked errors
    - staticcheck  # State-of-the-art static analysis
    - gosimple     # Suggests code simplifications
    - ineffassign  # Detects ineffectual assignments
    - unused       # Finds unused code
    - typecheck    # Parses and type-checks Go code

    # Security linters
    - gosec        # Inspects source code for security problems

    # Style linters
    - goimports    # Checks import ordering and formatting
    - gci          # Controls Go package import order
    - whitespace   # Checks for unnecessary whitespace

    # Best practices linters
    - gocritic     # Opinionated linter with many useful checks
    - revive       # Fast, configurable, extensible linter

linters-settings:
  # gofmt settings
  gofmt:
    # Use tabs (Go default)
    simplify: true

  # govet settings
  govet:
    # Enable all analyzers
    enable-all: true
    # Enable shadow checking to detect variable shadowing issues
    # Shadow checking helps prevent bugs where a variable is accidentally
    # redeclared in an inner scope, hiding the outer variable

  # errcheck settings
  errcheck:
    # Check for ignored errors with blank identifier
    check-blank: false
    # Check type assertions
    check-type-assertions: true
    # Exclude common patterns where error checking is intentionally skipped
    # These are functions whose return values are commonly (and safely) ignored
    exclude-functions:
      # fmt print functions - output errors are rarely actionable
      - fmt.Print
      - fmt.Printf
      - fmt.Println
      - fmt.Fprint
      - fmt.Fprintf
      - fmt.Fprintln
      # io.Closer - Close() errors on read-only resources are often ignored
      - (*os.File).Close
      - (io.Closer).Close
      - (*bufio.Reader).Reset
      - (*bufio.Writer).Flush
      # bytes.Buffer write operations never fail
      - (*bytes.Buffer).Write
      - (*bytes.Buffer).WriteByte
      - (*bytes.Buffer).WriteRune
      - (*bytes.Buffer).WriteString
      # strings.Builder write operations never fail
      - (*strings.Builder).Write
      - (*strings.Builder).WriteByte
      - (*strings.Builder).WriteRune
      - (*strings.Builder).WriteString
      # hash.Hash Write never returns an error
      - (hash.Hash).Write

  # staticcheck settings
  staticcheck:
    # Use the latest staticcheck checks
    checks: ["all"]

  # gosec settings - security linter
  gosec:
    # Include all rules by default
    includes: []
    # Exclude rules that may be too noisy for this codebase
    excludes: []
    # Exclude generated files
    exclude-generated: true
    # Severity of issues (low, medium, high)
    severity: medium
    # Confidence level (low, medium, high)
    confidence: medium

  # goimports settings
  goimports:
    # Put local imports after 3rd-party packages
    local-prefixes: github.com/r3d91ll

  # gci settings - import ordering
  gci:
    sections:
      - standard                       # Standard library imports
      - default                        # Third-party imports
      - prefix(github.com/r3d91ll)     # Local/project imports
    # Skip generated files
    skip-generated: true
    # Custom order for better readability
    custom-order: true

  # whitespace settings
  whitespace:
    # Enforce newlines at end of function bodies
    multi-func: false
    # Allow multiple empty lines in function bodies
    multi-if: false

  # gocritic settings - best practices
  gocritic:
    # Enable specific checker groups
    enabled-tags:
      - diagnostic
      - style
      - performance
    # Disable experimental checks (can be noisy)
    disabled-tags:
      - experimental
      - opinionated
    # Settings for specific checkers
    settings:
      captLocal:
        # Check for capitalized local variables
        paramsOnly: true
      rangeValCopy:
        # Size threshold for range value copy warning
        sizeThreshold: 32
      hugeParam:
        # Size threshold for parameter size warning
        sizeThreshold: 80

  # revive settings - extensible linter
  # Configured to match the WeaverTools codebase conventions
  revive:
    # Confidence threshold for issues
    confidence: 0.8
    # Severity for issues (warning or error)
    severity: warning
    # Enable all rules by default, then configure exceptions
    enable-all-rules: false
    rules:
      # === Essential Best Practices ===
      - name: blank-imports
        # Disallow blank imports except for side effects with comments
      - name: context-as-argument
        # Context should be the first parameter of a function
        arguments:
          - allowTypesBefore: "*testing.T"
      - name: context-keys-type
        # Context keys should be typed to avoid collisions
      - name: error-return
        # Error should be the last return value
      - name: error-strings
        # Error strings should not be capitalized or end with punctuation
      - name: error-naming
        # Error variables should be named errFoo or ErrFoo
      - name: exported
        disabled: false
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"
      - name: if-return
        # Avoid redundant else when if block ends with return
      - name: increment-decrement
        # Use ++ and -- instead of += 1 and -= 1
      - name: var-declaration
        # Simplify variable declarations when possible
      - name: range
        # Prefer range loops over index-based loops when possible
      - name: receiver-naming
        # Receiver names should be consistent and short
      - name: time-naming
        # Time variables should follow Go conventions
      - name: unexported-return
        # Exported functions should not return unexported types
      - name: indent-error-flow
        # Prefer early returns to reduce nesting
      - name: errorf
        # Use fmt.Errorf for error formatting
      - name: empty-block
        # Avoid empty code blocks
      - name: superfluous-else
        # Avoid else after if with break/continue/return
      - name: unreachable-code
        # Detect unreachable code
      - name: redefines-builtin-id
        # Don't redefine builtin identifiers
      # === Additional Safety Rules ===
      - name: dot-imports
        # Disallow dot imports (except for tests)
      - name: early-return
        # Prefer early returns to reduce nesting
      - name: confusing-naming
        # Avoid confusing variable and method names
      - name: modifies-value-receiver
        # Detect methods that modify value receivers (ineffective)
      - name: constant-logical-expr
        # Detect constant logical expressions (always true/false)
      - name: unnecessary-stmt
        # Detect unnecessary statements
      - name: defer
        # Check for common defer issues
        arguments:
          - ["call-chain", "loop", "recover"]
      - name: import-shadowing
        # Detect when local variables shadow imported packages
      - name: waitgroup-by-value
        # WaitGroup should not be passed by value
      - name: atomic
        # Check for common issues with sync/atomic
      # === Disabled Rules (intentionally relaxed) ===
      - name: package-comments
        disabled: true  # Enable when package comments are added
      - name: unused-parameter
        disabled: true  # Can be noisy with interface implementations
      - name: cognitive-complexity
        disabled: true  # Can be too restrictive for complex logic
      - name: cyclomatic
        disabled: true  # Similar to cognitive-complexity
      - name: function-length
        disabled: true  # Some functions are legitimately long
      - name: line-length-limit
        disabled: true  # gofmt handles this appropriately
      - name: max-public-structs
        disabled: true  # Not applicable to all packages
      - name: add-constant
        disabled: true  # Too aggressive for small constants
      - name: unhandled-error
        disabled: true  # errcheck handles this better

issues:

  # Maximum issues count per one linter (0 = unlimited)
  max-issues-per-linter: 0

  # Maximum count of issues with the same text (0 = unlimited)
  max-same-issues: 0

  # Exclude some checks for test files and generated code
  exclude-rules:
    # Test files - relax some checks
    - path: _test\.go
      linters:
        - errcheck      # Don't require checking all errors in tests
        - gosec         # Security checks less critical in tests
        - gocritic      # Relax style in tests
        - revive        # Relax best practices in tests

    # Generated code patterns - skip entirely
    - path: _gen\.go$
      linters:
        - goimports
        - gci
        - whitespace
        - gocritic
        - revive
        - gosec

    - path: \.pb\.go$
      linters:
        - goimports
        - gci
        - whitespace
        - gocritic
        - revive
        - gosec

    - path: generated
      linters:
        - goimports
        - gci
        - whitespace
        - gocritic
        - revive
        - gosec

    # Mock files - relax checks
    - path: mock.*\.go$
      linters:
        - gocritic
        - revive

    - path: _mock\.go$
      linters:
        - gocritic
        - revive

severity:
  # Set the default severity for issues
  default-severity: warning

  # Rules for changing issue severity
  rules:
    - linters:
        - errcheck
      severity: error
    - linters:
        - staticcheck
      severity: error
    - linters:
        - gosec
      severity: error    # Security issues should be treated as errors
    - linters:
        - govet
      severity: error    # Vet issues often indicate real bugs
