#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 025

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo "========================================"
echo "Test Environment Setup for WeaverTools"
echo "========================================"

# ============================================
# VERIFY PREREQUISITES
# ============================================

echo -e "\n${YELLOW}Checking prerequisites...${NC}"

# Check Go installation
if ! command -v go &> /dev/null; then
    echo -e "${RED}Go is not installed${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Go $(go version | awk '{print $3}')${NC}"

# Check Python installation
if ! command -v python3 &> /dev/null; then
    echo -e "${RED}Python is not installed${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Python $(python3 --version | awk '{print $2}')${NC}"

# Check Poetry installation (for TheLoom)
if ! command -v poetry &> /dev/null; then
    echo -e "${YELLOW}Poetry is not installed (needed for TheLoom)${NC}"
    echo "Install with: curl -sSL https://install.python-poetry.org | python3 -"
else
    echo -e "${GREEN}✓ Poetry $(poetry --version | awk '{print $3}')${NC}"
fi

# ============================================
# GO MODULE SETUP
# ============================================

echo -e "\n${YELLOW}Setting up Go modules...${NC}"

# Wool package
cd ./Wool
echo "Wool: go mod tidy"
go mod tidy
cd ..

# Weaver package
cd ./Weaver
echo "Weaver: go mod tidy"
go mod tidy
cd ..

# Yarn package (for regression testing)
cd ./Yarn
echo "Yarn: go mod tidy"
go mod tidy
cd ..

echo -e "${GREEN}✓ Go modules ready${NC}"

# ============================================
# PYTHON/THELOOM SETUP
# ============================================

echo -e "\n${YELLOW}Setting up TheLoom environment...${NC}"

cd ./TheLoom/the-loom

if command -v poetry &> /dev/null; then
    echo "Installing TheLoom dependencies..."
    poetry install
    echo -e "${GREEN}✓ TheLoom dependencies installed${NC}"
else
    echo -e "${YELLOW}⚠ Skipping TheLoom setup (Poetry not installed)${NC}"
fi

cd ../..

# ============================================
# E2E TEST SETUP
# ============================================

echo -e "\n${YELLOW}Setting up E2E test directory...${NC}"

mkdir -p ./tests/e2e
cd ./tests/e2e

# Initialize go module if it doesn't exist
if [ ! -f "go.mod" ]; then
    echo "Initializing E2E test module..."
    go mod init github.com/weavertools/tests/e2e
    echo -e "${GREEN}✓ E2E test module initialized${NC}"
else
    echo -e "${GREEN}✓ E2E test module exists${NC}"
fi

cd ../..

# ============================================
# VERIFICATION
# ============================================

echo -e "\n${YELLOW}Running smoke tests...${NC}"

# Verify Wool compiles
echo -n "Wool: "
cd ./Wool && go build ./... && echo -e "${GREEN}OK${NC}" || echo -e "${RED}FAIL${NC}"
cd ..

# Verify Weaver compiles
echo -n "Weaver: "
cd ./Weaver && go build ./... && echo -e "${GREEN}OK${NC}" || echo -e "${RED}FAIL${NC}"
cd ..

# Verify Yarn tests (regression check)
echo -n "Yarn tests: "
cd ./Yarn && go test ./... > /dev/null 2>&1 && echo -e "${GREEN}OK (baseline)${NC}" || echo -e "${YELLOW}WARN${NC}"
cd ..

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Test Commands:"
echo ""
echo "  # Wool tests (new test suite)"
echo "  cd Wool && go test -v -race -cover ./..."
echo ""
echo "  # Weaver spinner tests (fix 3 failures)"
echo "  cd Weaver && go test -v ./pkg/spinner"
echo ""
echo "  # TheLoom non-GPU tests (enable CI)"
if command -v poetry &> /dev/null; then
    echo "  cd TheLoom/the-loom && poetry run pytest -v -m 'not gpu'"
else
    echo "  (Poetry required - not available)"
fi
echo ""
echo "  # E2E tests (automation)"
echo "  cd tests/e2e && go test -v ./..."
echo ""
echo "  # Regression check (Yarn baseline)"
echo "  cd Yarn && go test ./..."
echo ""
echo "Parallel Implementation:"
echo "  source auto-claude/.venv/bin/activate"
echo "  python auto-claude/run.py --spec 025 --parallel 3"
echo ""
